---
job: extension
config:
  # this name will be the folder and filename name
  name: "linyitong_v4"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "/root/ai-toolkit/modal_output" # must match MOUNT_DIR from run_modal.py
      # uncomment to see performance stats in the terminal every N steps
      performance_log_every: 50
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "linyitong"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 # precision to save
        save_every: 250 # save every this many steps
        max_step_saves_to_keep: 4 # how many intermittent saves to keep
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        # your dataset must be placed in /ai-toolkit and /root is for modal to find the dir:
        - folder_path: "/root/ai-toolkit/linyitong_v4"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 4000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        # if you get an error, or get stuck while downloading,
        # check https://github.com/ostris/ai-toolkit/issues/84, download the model locally and
        # place it like "/root/ai-toolkit/FLUX.1-dev"
        # name_or_path: "black-forest-labs/FLUX.1-dev"
        name_or_path: "/root/FLUX.1-dev"
        is_flux: true
        quantize: false  # run 8bit mixed precision
#        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 250 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          - "linyitong, sitting on a chair with a slightly playful expression, her slender legs are accentuated by black stockings and high heels, in a room with natural lighting, professional photograph style, her physique has a well-proportioned silhouette, and her distinct facial features are clearly visible."
          - "linyitong, seated on a wooden chair in a well-lit room, striking a pose with a soft smile, photographed in a professional portrait style, demonstrating a well-proportioned figure, slender legs, and a noticeable silhouette, her body features consistently highlighted in the photograph, captured with attention to anatomical details, using soft lighting to enhance her physical attributes and complexion, focus on the photographic clarity of her distinctive features."
          - "linyitong, photographed outdoors in a white bikini top, gazing directly at the camera with a calm expression, slender arms and smooth skin, standing with one hand resting on her head, long black hair cascading down her chest, full bust with a visible cleavage line, natural lighting enhances her soft features, swimsuit highlighting her figure, high-resolution photograph capturing her detailed facial structure and upper body proportions."
        neg: ""  # not used on flux
        seed: -1  # 使用随机种子而不是固定种子，以便每次样本有更多变化
        walk_seed: true
        guidance_scale: 4
        sample_steps: 28
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
  # Training optimization notes
  comments: "Configuration optimized for Flux model. Adjusted parameters to show more visible progress in sample images during training."
